### ISSUE TITLE
Problem with seeder

### ISSUE THREAD

**Issue by Onicaro** [scfmod/FS22_advancedGameplaySettings#2]
Hi! I don't know if this problem is only with the Amazone Citan 150001-C, but your mod makes it impossible to turn it. 
![image](https://user-images.githubusercontent.com/22916106/146102273-bde19f00-d412-4734-ac7a-3ee5ca0110d5.png)
Hopefully the problem is only with this specific seeder and not others implements in the game, cause I love your mod! Thank you.

**Comment by scfmod** [comment]
I will check it out later today! :-)

**Comment by scfmod** [comment]
Just tested the seeder and it works fine :-)  Maybe you have a another mod that interferes with that seeder?

**Comment by Onicaro** [comment]
I only have your mod activated. I even tried on two new saves and the same happens again. 

This is the log of my last test
[log.txt](https://github.com/scfmod/FS22_advancedGameplaySettings/files/7722511/log.txt)

Any suggestions on what it might be?

**Comment by scfmod** [comment]
Ohh I noticed something weird now testing it again, seems like the attach joint messes up. I'll check what causes it

**Comment by scfmod** [comment]
Turns out there was a small logic bug in the frontloader fix function! Thanks for reporting, pushing up new version now

**Comment by Tubezki** [comment]
Thank you for already taking a look! I was playing with my friend in multiplayer today and we had this same problem so I started to investigate your mod as well and came up with same thing that it got to do with frontloader fix. I hope you can fix this problem without removing that frontloader fix because I hate to play this game with frontloaders when the suspension is not working correctly and its locked like in retail game!

**Comment by scfmod** [comment]
Yeah locking the front suspension is just horrible to play with! The fix is out, it should work just fine now :-)

**Comment by Tubezki** [comment]
Thank you, your mod is auctually very very important for many players and I hope you keep developing it! Testing it right away. Btw this is just a suggestion from me but what would you think about this idea that adding multiply value to manipulate weight of the tractor and also, the tool/tools that are connected to it? I mean like you could add mass calculator that multiply current weight a bit more because everything feels so light right now... I know there is this KG mod already out but not sure if it works like this way?

**Comment by scfmod** [comment]
Glad to hear ye be enjoying it!
It's definately doable to manipulate the mass, but should be a separate mod considering it could really mess up stuff :-D
I'll stick it in my maybe mod list! If ye got other ideas for improvements/features just post em as a new issue 👍

**Comment by Onicaro** [comment]
Thank you @scfmod! You rock.
